// <auto-generated />
namespace Diligent.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ChangeCategorytoProjectuseprojectasconnectionbetweenuserandtask : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ChangeCategorytoProjectuseprojectasconnectionbetweenuserandtask));
        
        string IMigrationMetadata.Id
        {
            get { return "201708011509369_Change Category to Project, use project as connection between user and task"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
